services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - model_cache:/app/cache
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  model_cache:
